### ISSUE TITLE
ubuntu14.04: selinux permissve mode fails

### ISSUE THREAD

**Issue by gdha** [gdha/rear-automated-testing#31]
````
TASK [rear-test : change the selinux to permissive] ****************************
fatal: [server]: FAILED! => {"changed": false, "failed": true, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
````
The task where the problem pops up:
````
# ansible/common/roles/rear-test/tasks/change_selinux_state.yml

- name: change the selinux to permissive
  selinux:
    policy: targeted
    state: permissive
````
With centos7 and ubuntu16 we do not have this issue
