### ISSUE TITLE
Ubuntu18.04: change the selinux to permissive (ubuntu >14) ansible task fails

### ISSUE THREAD

**Issue by gdha** [gdha/rear-automated-testing#73]
TASK [rear-test : change the selinux to permissive (ubuntu >14)] ***************
fatal: [server]: FAILED! => {"changed": false, "msg": "Policy targeted does not exist in /etc/selinux/"}

**Comment by gdha** [comment]
The task that fails is:
````
- name: change the selinux to permissive (ubuntu >14)
  selinux:
    policy: targeted
    state: permissive
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version > '14'
````
